### ISSUE TITLE
[FEAT] 负载均衡

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi-plugin-genshin#5]
目前米游社查询，单个账号的查询上限为 30 个不同的玩家（不包括自己），当查询达到上限以后就会报错。因此需要设计负载均衡方案。

## 目标

- [x] 允许保存多个账号
- [x] 当前账号达到上限以前自动切换到下一个账号
- [x] 通过指令配置账号信息
- [x] 当前账号达到上限或报错后自动切换账号进行查询

**Comment by dragon-fish** [comment]
## 数据库结构

```yml
uid: <genshin_uid>
owner: <type>:<pid>
enable: <boolean>
lastdate: <yyyy-MM-dd>
limit: <0-29>
usage: 
  - <uid>
  - <uid>
  # ...
```
